export const randomTherapists = [
  {
    email: 'therapist1@mail.com',
    password: 'password1',
    firstName: 'Therapist',
    lastName: 'One',
    language: 'English',
    specialization: 'Psychologist',
  },
  {
    email: 'therapist2@mail.com',
    password: 'password1',
    firstName: 'Therapist',
    lastName: 'Two',
    language: 'Spanish',
    specialization: 'Family Therapist',
  },
  {
    email: 'therapist3@mail.com',
    password: 'password1',
    firstName: 'Therapist',
    lastName: 'Three',
    language: 'French',
    specialization: 'Couples Counselor',
  },
  {
    email: 'therapist4@mail.com',
    password: 'password1',
    firstName: 'Therapist',
    lastName: 'Four',
    language: 'English',
    specialization: 'Psychologist',
  },
  {
    email: 'therapist5@mail.com',
    password: 'password1',
    firstName: 'Therapist',
    lastName: 'Five',
    language: 'Spanish',
    specialization: 'Family Therapist',
  },
  {
    email: 'therapist6@mail.com',
    password: 'password1',
    firstName: 'Therapist',
    lastName: 'Six',
    language: 'French',
    specialization: 'Couples Counselor',
  },
  {
    email: 'therapist7@mail.com',
    password: 'password1',
    firstName: 'Therapist',
    lastName: 'Seven',
    language: 'English',
    specialization: 'Psychologist',
  },
  {
    email: 'therapist8@mail.com',
    password: 'password1',
    firstName: 'Therapist',
    lastName: 'Eight',
    language: 'Spanish',
    specialization: 'Family Therapist',
  },
  {
    email: 'therapist9@mail.com',
    password: 'password1',
    firstName: 'Therapist',
    lastName: 'Nine',
    language: 'French',
    specialization: 'Couples Counselor',
  },
];
